spring:
  aop:
    auto: true

# 数据源
  datasource:
    druid:
      url: jdbc:mysql://localhost/polo?useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Hongkong
      username: root
      password: root
      initial-size: 5
      max-active: 20
      min-idle: 5
      max-wait: 6000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 30

  servlet:
    # 上传文件大小
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

# mybatis
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath*:com/**/dao/mapper/*.xml

